import React from 'react'

export const metadata = {
  title: 'Test Page',
  description: 'Generated by create next app(Test Page)',
}

export default function Testpage() {
  return (
    <main>
      <nav className="mb-1 pb-1">
        <div className="block">
          <h2 className="content-center text-2xl">Test Page</h2>
          <div><small>Showcasing Test page</small></div>
        </div>
      </nav>
    </main>
  )
}
